name: Test on Push to Main

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - uses: php-actions/composer@v6

    - name: PHPUnit Tests
      uses: php-actions/phpunit@master
      env:
        XDEBUG_MODE: coverage
      with:
        php_extensions: GD xdebug
        version: 9.6.11
        coverage_cobertura: coverage.xml
        

    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage.xml
        format: markdown 
        output: file
    
    - name: Adding markdown
      run: cat 'code-coverage-results.md' >> $GITHUB_STEP_SUMMARY

    - name: PHP Code Sniffer
      uses: php-actions/phpcs@v1
      with:
        php_version: 8.1
        path: lib/
        standard: psr1 
